# Generated by Django 3.0.1 on 2019-12-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original',
            field=models.CharField(max_length=500),
        ),
    ]
